imports:
    - { resource: config.yml }

monolog:
    handlers:
        syrup_syslog:
            type: syslog
            ident: %app_name%
            level: info
            channels: ["!request", "!event", "!doctrine"]
            formatter: syrup.monolog.formatter
        storage_api:
            type: service
            id: syrup.monolog.sapi_handler
            ident: %app_name%
            level: info
            channels: ["!request", "!event", "!doctrine"]