keboola_syrup_index:
    path:      /
    defaults:  { _controller: SyrupBundle:Index:index }

keboola_syrup_core:
    resource: .
    type: component

keboola_syrup_api_options:
    path:     /{params}
    defaults: { _controller: SyrupBundle:Api:options, params: 0, _format: json }
    methods:  [OPTIONS]
    requirements:
        params: ".+"

keboola_syrup_api_run:
    path:     /{componentName}/run
    defaults: { _controller: SyrupBundle:Api:run, _format: json }
    methods:  [POST]

keboola_syrup_not_found:
    path:      /{path}
    defaults:  { _controller: SyrupBundle:Index:notFound }
    requirements:
        path: .*
